### ISSUE TITLE
Add an option to be more permissive with extra fields for manifest parsing

### ISSUE THREAD

**Issue by aballiet** [yu-iskw/dbt-artifacts-parser#103]
DBT Cloud released a [versionless](https://docs.getdbt.com/docs/dbt-versions/versionless-cloud) deployment mode which rollout update on Manifest it seems. It adds new properties.

You can check schema here: https://schemas.getdbt.com/dbt/manifest/v12.json

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/b84f4422-f772-401b-83e9-df9f84c98250">

I think we should be more permissive with it, allowing users to specify if extra fields should be blocking or not. I guess in vast majority of cases (lineage parsing tools like https://github.com/open-metadata/OpenMetadata) it should not be blocking.

**Comment by MiConnell** [comment]
I agree, I was just struggling with this issue. I opened a PR (#104) to update the default to `allow` from `forbid`

**Comment by jtcohen6** [comment]
+1 from the dbt team. This permissiveness would be better aligned with our philosophy that adding a new field (with a default) is a non-breaking change, and therefore does not require a major-version bump to artifacts: https://docs.getdbt.com/blog/latest-dbt-stability#stability-for-metadata-artifacts

From the [dbt-core artifacts README](https://docs.getdbt.com/blog/latest-dbt-stability#stability-for-metadata-artifacts):

> **Non-breaking changes**
> Freely make incremental, non-breaking changes in-place to the latest major version of any artifact (minor or patch bumps). The only changes that are fully forward and backward compatible are:
>
> - Adding a new field with a default
> - Deleting a field with a default
>
> ...
>
> Note: Although jsonschema validation using the schemas in [schemas.getdbt.com](https://schemas.getdbt.com/) is not encouraged or formally supported, jsonschema validation should still continue to work once the schemas are updated because they are forward-compatible and can therefore be used to validate previous minor versions of the schema.

**Comment by jtcohen6** [comment]
+1 from the dbt team. This permissiveness would be better aligned with our philosophy that adding a new field (with a default) is a non-breaking change, and therefore does not require a major-version bump to artifacts: https://docs.getdbt.com/blog/latest-dbt-stability#stability-for-metadata-artifacts

From the [dbt-core artifacts README](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/artifacts/README.md#non-breaking-changes)

> **Non-breaking changes**
> Freely make incremental, non-breaking changes in-place to the latest major version of any artifact (minor or patch bumps). The only changes that are fully forward and backward compatible are:
>
> - Adding a new field with a default
> - Deleting a field with a default
>
> ...
>
> Note: Although jsonschema validation using the schemas in [schemas.getdbt.com](https://schemas.getdbt.com/) is not encouraged or formally supported, jsonschema validation should still continue to work once the schemas are updated because they are forward-compatible and can therefore be used to validate previous minor versions of the schema.

**Comment by yu-iskw** [comment]
I understand the philosophy. I wnat to clarify two things about extra fields. 

1. Should we allow to add a new fields in anywhere at any level? 
2. I feel this can be controlled by the JSON schemas of dbt artifacts.

First, I want to know the philosophy is applied to any fields at any level? For instance, it sounds natural to allow extra fields in `meta` properties. But, I am personally upset to allow extra fields at any level. 

Second, we can control to allow additional fields by the JSON schema of dbt artifacts. For instance, the `columns` property in a node has the `additionalProperties: true` property. So, the generated class has extra fields. I feel it would be good to clearly define where we can use additional fields in dbt artifacts. We can technically customize the generatec classes from the JSON schema of dbt artifacts. But, it would be a bit difficult to settle what we can customize in the package. I want to keep generated classes from the schemas as original as possible, because it is a bit hassle to manage the additional changes in generating code.

I totally understand that it is quite difficult to change the JSON schema of dbt artifacts of the older versions in the dbt-core repository. But, I want to change [the JSON schemas](https://github.com/yu-iskw/dbt-artifacts-parser/tree/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/resources), not generatec class, in the repository. 

- https://github.com/yu-iskw/dbt-artifacts-parser/blob/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/resources/manifest/manifest_v12.json#L572C19-L572C48
- https://github.com/yu-iskw/dbt-artifacts-parser/blob/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/parsers/manifest/manifest_v12.py#L141

**Comment by aballiet** [comment]
> I understand the philosophy. I wnat to clarify two things about extra fields.
> 
> 1. Should we allow to add a new fields in anywhere at any level?
> 2. I feel this can be controlled by the JSON schemas of dbt artifacts.
> 
> First, I want to know the philosophy is applied to any fields at any level? For instance, it sounds natural to allow extra fields in `meta` properties. But, I am personally upset to allow extra fields at any level.
> 
> Second, we can control to allow additional fields by the JSON schema of dbt artifacts. For instance, the `columns` property in a node has the `additionalProperties: true` property. So, the generated class has extra fields. I feel it would be good to clearly define where we can use additional fields in dbt artifacts. We can technically customize the generatec classes from the JSON schema of dbt artifacts. But, it would be a bit difficult to settle what we can customize in the package. I want to keep generated classes from the schemas as original as possible, because it is a bit hassle to manage the additional changes in generating code.
> 
> I totally understand that it is quite difficult to change the JSON schema of dbt artifacts of the older versions in the dbt-core repository. But, I want to change [the JSON schemas](https://github.com/yu-iskw/dbt-artifacts-parser/tree/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/resources), not generatec class, in the repository.
> 
> * https://github.com/yu-iskw/dbt-artifacts-parser/blob/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/resources/manifest/manifest_v12.json#L572C19-L572C48
> * https://github.com/yu-iskw/dbt-artifacts-parser/blob/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/parsers/manifest/manifest_v12.py#L141

Agree that the best is to handle extra fields policy in JSON Schema directly but currently it's not the case.

IMO for now as a temporary fix to make your package relevant for most users, we should allow at any-level to make sure parsing is handled.

You could think about an extra parameter for the function https://github.com/yu-iskw/dbt-artifacts-parser/blob/7ac8c85474cb1c19b1ef75ee422e81c701eafb99/dbt_artifacts_parser/parser.py#L74 like `forbid_extra_fields` default to `false`

**Comment by aballiet** [comment]
> > but currently it's not the case.
> 
> Can you elaborate on it? I am still upset to apply a temporary solution due to the two reasons:
> 
> 1. it is hard to manage manual changes to generated files, because we have to apply them every time when we regenerate classes.
> 2. The official schemas explicitely declare `"additionalProperties": false`. I want to admire the official declarations as much as possible. We use the datamodel-code-generator package to generatge classes from the JSON schema. It doesn't specify the model configuration about extra fields, if the "additionalProperties" properties are set.
>     - e.g. manifest v12: https://github.com/dbt-labs/dbt-core/blob/main/schemas/dbt/manifest/v12.json#L559
> 
> I totally understand some users want to the temporary changes for extra fields. Meanwhile, we have to beare in mind other users to validate their inputs with the strict properties. 

Totally agree with you and I am not from dbt labs.

Maybe @jtcohen6 could answer this one on why dbt do not write their jsonschema with this in mind as agree with you it's the purpose of schemas.

Will also ask their dbt cloud support...

**Comment by yu-iskw** [comment]
@aballiet BTW, can you tell me what kind of extra fields you want to add? I want to enchance the resolution about what some users want to do with the package.

**Comment by aballiet** [comment]
> @aballiet BTW, can you tell me what kind of extra fields you want to add? I want to enchance the resolution about what some users want to do with the package. It would be good to give feedback not only to the repository, but also the dbt community, as we can also change the official JSON schemas in the dbt-core repository. That might be helpful for other dbt users as well.

```bash
curl https://schemas.getdbt.com/dbt/manifest/v12.json -o json_schema_v12.json
datamodel-codegen  --input json_schema_v12.json --input-file-type jsonschema --output model.py
```

**Comment by yu-iskw** [comment]
In that case, how about validating  your artifacts with the official JSON schemas using something like check-jsonschema. By doing this, we can break down the issue. If you see any issues just on the validation, I would be great to give feedback to the dbt community and dbt Labs.

https://github.com/python-jsonschema/check-jsonschema

**Comment by aballiet** [comment]
NVM they fixed on DBT Cloud side, now manifest parser works as expected 👍. Closing the issue

**Comment by hashboard-charlie** [comment]
I'm pretty surprised by the resolution of this issue. The fact that DBT Cloud (temporarily) rolled back the specific additions isn't reflective that the issue here was fixed.

- The DBT team explicitly calls out that they reserve the right to append extra fields to the manifest without a version bump, and DBT Cloud will emit such artifacts without first signaling to this project.
- The JSON schemas are encoded into this project as Python models, not pulled dynamically.

As I understand it, **that means that anytime DBT Cloud updates their artifacts with new properties, this project will _always_ begin to fail until it is updated and consumers update against it.**

That's a problem that can be solved on a client side by allowing consumers to opt into a looser set of restrictions, ie. to expect the artifact to match a known _interface_, instead of look _exactly_ a certain way.

I understand the philosophy of using `additionalProperties: false`, but this property is most often used to signal object maps with a strongly typed value type, not that a particular object is _frozen_ now and forever ([DBT aligns with that here](https://github.com/yu-iskw/dbt-artifacts-parser/issues/103#issuecomment-2285148614)). DBT's own documentation and their Cloud implementation is certainly a better source of truth for what to do with these properties than the spec file they themselves indicate "is not encouraged or formally supported".

**Comment by hashboard-charlie** [comment]
Below is a very dirty workaround for anybody waiting on a solution here. Calling this before using `dbt_artifacts_parser` will monkey patch it so that all top level and nested types will ignore additional properties.

```py
def _patch_dbt_artifact_parser():
    """
    Patch over the base model which `dbt_artifacts_parser` uses in order
    to force the `extra` setting to be permissive instead of forbidden.

    See https://github.com/yu-iskw/dbt-artifacts-parser/issues/103
    """
    from dbt_artifacts_parser.parsers.base import BaseParserModel
    from pydantic import Extra

    original_init = BaseParserModel.__init__

    def override__init__(__pydantic_self__, **data) -> None:
        if __pydantic_self__.__class__.__config__.extra == Extra.forbid:
            __pydantic_self__.__class__.__config__.extra = Extra.ignore
        original_init(__pydantic_self__, **data)

    BaseParserModel.__init__ = override__init__
```

**Comment by yu-iskw** [comment]
@hashboard-charlie Good insight and thank you for sharing the workaround.

I think there might be another point on it besides the issue. We use the JSON schemas of dbt Core, not dbt Cloud. The philosophy on dbt artifacts can be aligned between dbt Core and dct Cloud. But, Potentially, schemas of them can't be completely compatible due to the additional features of dbt Cloud. If that case happens. This project can't catch up with specifications of dbt Cloud, because the JSON schemas of dbt Cloud aren't open-sourced. So, it would be difficult to completely support to parse artifacts of dbt Cloud in this package.
