### ISSUE TITLE
Base Classes

### ISSUE THREAD

**Issue by judahrand** [yu-iskw/dbt-artifacts-parser#20]
I'm not really sure how this would work, however, it might be nice to be able to have base classes for the various artifacts which would allow for better type hinting than `BaseModel`.

I'm open to ideas and open to helping.

**Comment by yu-iskw** [comment]
Can you elaborate on that? I would like to know use cases with base classes of each artifacts respectibly. 

In reality, generated classes for dbt artifacts don't directly inherit `BaseModel` so that we can implement something common among the classes of artifacts. However, I haven't seen any cases for that.

- https://github.com/yu-iskw/dbt-artifacts-parser/blob/000344a47a724d498a4d7d2d82fd60b8ac5f4fa8/dbt_artifacts_parser/parsers/base.py

**Comment by judahrand** [comment]
My use case is that I'm looking to build a tool which exposes the artifacts via a GraphQL API (https://github.com/judahrand/dbt-metadata-api). My first pass is trying to replicate the dbt Metadata API, though I'm not sure this is the best approach... 

During development it is handy to hand type hints sort themselves out so that one gets autocomplete on them. For now I've just defined my own `Union[ManifestV5, ManifestV6, ManifestV7]` type and used that. This might even be the best approach... However, I also wonder if it would be possible to define a `BaseManifest` which is an abstract class which defines the common functionality between all the other classes?

**Comment by yu-iskw** [comment]
@judahrand Thank you for the explanation. I see your point.

I'm not sure whether or not that works by using something like `BaseManifest`. As you know, we take advantage of `datamodel-codegen` commands in the `datamodel-code-generator` module to generate pydantic-based classes. Even a classe to a nested field inherit a specified base class. Since we pass the `BaseParserClass` class to `datamodel-codegen` commands in our case, all nested fields inherit the class. I am worried about type hinting gets confused due to a lot of inherited different classes.
- https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parsers/manifest/manifest_v6.py#L45

If you are sure it wold work to create abstract classes by artifact type, I don't mind to refactor the code generation.

**Comment by judahrand** [comment]
Unfortunately, at the moment I've moved away from using this package and instead am using `dbt-core` to parse the artifacts so I don't think I'll have much time to look into this.

**Comment by yu-iskw** [comment]
Alright. Let's close the issue.
