### ISSUE TITLE
resource_type not defined correctly for manifest v11

### ISSUE THREAD

**Issue by OnkarVO7** [yu-iskw/dbt-artifacts-parser#67]
In the manifest v11, resource_type parameter for ModelNode is defined as `Any` [here](https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parsers/manifest/manifest_v11.py#L1010). Due to this the actual value from manifest.json maps as a `str` type in pydantic model.

In the previous manifest v10,v9 this used to be mapped as an enum in python. Example [here](https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parsers/manifest/manifest_v10.py#L829) and [here](https://github.com/yu-iskw/dbt-artifacts-parser/blob/main/dbt_artifacts_parser/parsers/manifest/manifest_v9.py#L668C5-L668C18)

This is causing dtype mismatching while processing the v11 manifest. 

Solution would be to convert the v11 resource_type attribute to `enum` instead of `any`

@yu-iskw

**Comment by yu-iskw** [comment]
@OnkarVO7 Thank you for raising it. I want to address the short-term solution and the mid/long-term solution. What do you think?

- Short-term: Let's tentatively, manually replace them. As we automatically generate the pydantic classes from the manifest JSON, we have to manually catch up with changes in dbt Core.
- Mid/Long-term: I will make a proposal to improve the JSON schema of manifest v11 to dbt Core so that we can automatically generate the pydantic class with the desired data type(s).

**Comment by OnkarVO7** [comment]
Thanks @yu-iskw that sounds good.

For long term, definitely a generalised approach would help in maintaining the manifest versions.

**Comment by yu-iskw** [comment]
@OnkarVO7 I don't have much time to solve the issue. Can you address the short-term solution on behalf of me?

**Comment by pmbrull** [comment]
@OnkarVO7 let's take a look at this and see if we can help fix it
